# Generated by Django 3.2 on 2022-12-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20221214_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(related_name='title', through='reviews.GenreTitle', to='reviews.Genre'),
        ),
    ]
