# Generated by Django 3.2 on 2022-12-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_title_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='category',
            new_name='categorie',
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(),
        ),
    ]
